### ISSUE TITLE
gnuradio installation

### ISSUE THREAD

**Issue by laithmatalkah** [AFITWiSec/EZ-Wave#2] opened 2016-02-27 05:12 UTC
I'am a beginner in this field .  where should you recommend install gnuradio
in /home/user/  or in the root directory?? please provide me an example by using pybombs. I am so confused, because  everything was going well until I run ./install.sh blocks in scapy radio. 

something called grcc and gnuradio run-time are missing

**Comment by gitjhall** [comment] 2016-02-27 13:12
Duplicate of https://github.com/AFITWiSec/EZ-Wave/issues/1

**Closed by gitjhall** 2016-02-27 13:12 UTC
Labels: duplicate
